"""create research requests table

Revision ID: b5d8bd74ded8
Revises: a438adbe6c40
Create Date: 2026-08-06 16:10:13.691875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5d8bd74ded8'
down_revision: Union[str, Sequence[str], None] = 'a438adbe6c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='research_status'), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_requests_company_id'), 'research_requests', ['company_id'], unique=False)
    op.create_index(op.f('ix_research_requests_status'), 'research_requests', ['status'], unique=False)
    op.create_index(op.f('ix_research_requests_user_id'), 'research_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_requests_user_id'), table_name='research_requests')
    op.drop_index(op.f('ix_research_requests_status'), table_name='research_requests')
    op.drop_index(op.f('ix_research_requests_company_id'), table_name='research_requests')
    op.drop_table('research_requests')
    # ### end Alembic commands ###
