const LABELS: Record<string, string> = {
  accepted: 'Accepted',
  approved: 'Approved',
  business_identity_confirmed: 'Business identity confirmed',
  collected_evidence: 'Collected evidence',
  company_website: 'Company website',
  contact_form: 'Contact form',
  contacted: 'Contacted',
  dental_clinic: 'Dental clinic',
  draft: 'Draft',
  email: 'Email',
  excluded: 'Excluded',
  facebook: 'Facebook',
  failed: 'Failed',
  instagram: 'Instagram',
  interested: 'Interested',
  linkedin: 'LinkedIn',
  local_places: 'Business listing',
  not_a_fit: 'Not a fit',
  needs_research: 'Needs research',
  needs_review: 'Needs review',
  no_action: 'No action needed',
  no_response: 'No response',
  official_website: 'Official website',
  open_places: 'Open Places',
  pagespeed_insights: 'PageSpeed Insights',
  pending: 'Pending',
  phone: 'Phone',
  prepare_outreach: 'Prepare outreach',
  ready_for_outreach: 'Ready for outreach',
  replied: 'Replied',
  research_prospect: 'Research prospect',
  collect_evidence: 'Collect evidence',
  saved: 'Saved',
  sent: 'Sent',
  social_search: 'Social profile',
  apify: 'Apify',
  serper: 'Serper',
  tavily: 'Tavily',
  tiktok: 'TikTok',
  unavailable: 'Unavailable',
  verified: 'Verified',
  web_search: 'Web search',
  whatsapp: 'WhatsApp',
}

export function displayLabel(value: string): string {
  return LABELS[value] ?? value
    .replace(/[._-]+/g, ' ')
    .replace(/^\w/, (character) => character.toUpperCase())
}
